export const mobileOnly = {
    // Classes que só funcionam em mobile (< 480px)
    margin: {
      mb2: 'max-xs:mb-2',
      mb4: 'max-xs:mb-4',
      mb6: 'max-xs:mb-6',
      mb8: 'max-xs:mb-8',
      mb12: 'max-xs:mb-12',
      mb16: 'max-xs:mb-16',
      mb24: 'max-xs:mb-24',
      mb32: 'max-xs:mb-32',
      mt2: 'max-xs:mt-2',
      mt4: 'max-xs:mt-4',
      mt6: 'max-xs:mt-6',
      mt8: 'max-xs:mt-8',
      mt12: 'max-xs:mt-12',
      mt16: 'max-xs:mt-16',
      mt24: 'max-xs:mt-24',
      mt32: 'max-xs:mt-32',
    },
    padding: {
      p2: 'max-xs:p-2',
      p4: 'max-xs:p-4',
      p6: 'max-xs:p-6',
      p8: 'max-xs:p-8',
      p12: 'max-xs:p-12',
      p16: 'max-xs:p-16',
      p24: 'max-xs:p-24',
      p32: 'max-xs:p-32',
      px2: 'max-xs:px-2',
      px4: 'max-xs:px-4',
      px6: 'max-xs:px-6',
      px8: 'max-xs:px-8',
      px12: 'max-xs:px-12',
      px16: 'max-xs:px-16',
      py2: 'max-xs:py-2',
      py4: 'max-xs:py-4',
      py6: 'max-xs:py-6',
      py8: 'max-xs:py-8',
      py12: 'max-xs:py-12',
      py16: 'max-xs:py-16',
    },
    display: {
      hidden: 'max-xs:hidden',
      block: 'max-xs:block',
      flex: 'max-xs:flex',
      grid: 'max-xs:grid',
      inline: 'max-xs:inline',
      inlineBlock: 'max-xs:inline-block',
      inlineFlex: 'max-xs:inline-flex',
    },
    flex: {
      col: 'max-xs:flex-col',
      row: 'max-xs:flex-row',
      wrap: 'max-xs:flex-wrap',
      nowrap: 'max-xs:flex-nowrap',
      center: 'max-xs:items-center max-xs:justify-center',
      between: 'max-xs:justify-between',
      start: 'max-xs:justify-start',
      end: 'max-xs:justify-end',
    },
    text: {
      xs: 'max-xs:text-xs',
      sm: 'max-xs:text-sm',
      base: 'max-xs:text-base',
      lg: 'max-xs:text-lg',
      xl: 'max-xs:text-xl',
      '2xl': 'max-xs:text-2xl',
      '3xl': 'max-xs:text-3xl',
      '4xl': 'max-xs:text-4xl',
      center: 'max-xs:text-center',
      left: 'max-xs:text-left',
      right: 'max-xs:text-right',
    },
    width: {
      full: 'max-xs:w-full',
      half: 'max-xs:w-1/2',
      third: 'max-xs:w-1/3',
      quarter: 'max-xs:w-1/4',
      auto: 'max-xs:w-auto',
    },
    height: {
      full: 'max-xs:h-full',
      screen: 'max-xs:h-screen',
      auto: 'max-xs:h-auto',
      h16: 'max-xs:h-16',
      h20: 'max-xs:h-20',
    },
    position: {
      relative: 'max-xs:relative',
      absolute: 'max-xs:absolute',
      fixed: 'max-xs:fixed',
      sticky: 'max-xs:sticky',
    },
    grid: {
      cols1: 'max-xs:grid-cols-1',
      cols2: 'max-xs:grid-cols-2',
      cols3: 'max-xs:grid-cols-3',
      cols4: 'max-xs:grid-cols-4',
      gap2: 'max-xs:gap-2',
      gap4: 'max-xs:gap-4',
      gap6: 'max-xs:gap-6',
      gap8: 'max-xs:gap-8',
    },
    gap: {
      gap2: 'max-xs:gap-2',
      gap4: 'max-xs:gap-4',
      gap6: 'max-xs:gap-6',
      gap8: 'max-xs:gap-8',
      gap10: 'max-xs:gap-10',
    },
  };
  
  export const desktopOnly = {
    // Classes que só funcionam em desktop (≥ 1024px)
    margin: {
      mb2: 'lg:mb-2',
      mb4: 'lg:mb-4',
      mb6: 'lg:mb-6',
      mb8: 'lg:mb-8',
      mb12: 'lg:mb-12',
      mb16: 'lg:mb-16',
      mb24: 'lg:mb-24',
      mb32: 'lg:mb-32',
      mt2: 'lg:mt-2',
      mt4: 'lg:mt-4',
      mt6: 'lg:mt-6',
      mt8: 'lg:mt-8',
      mt12: 'lg:mt-12',
      mt16: 'lg:mt-16',
      mt24: 'lg:mt-24',
      mt32: 'lg:mt-32',
    },
    padding: {
      p2: 'lg:p-2',
      p4: 'lg:p-4',
      p6: 'lg:p-6',
      p8: 'lg:p-8',
      p12: 'lg:p-12',
      p16: 'lg:p-16',
      p24: 'lg:p-24',
      p32: 'lg:p-32',
      px2: 'lg:px-2',
      px4: 'lg:px-4',
      px6: 'lg:px-6',
      px8: 'lg:px-8',
      px12: 'lg:px-12',
      px16: 'lg:px-16',
      py2: 'lg:py-2',
      py4: 'lg:py-4',
      py6: 'lg:py-6',
      py8: 'lg:py-8',
      py12: 'lg:py-12',
      py16: 'lg:py-16',
    },
    display: {
      hidden: 'lg:hidden',
      block: 'lg:block',
      flex: 'lg:flex',
      grid: 'lg:grid',
      inline: 'lg:inline',
      inlineBlock: 'lg:inline-block',
      inlineFlex: 'lg:inline-flex',
    },
    flex: {
      col: 'lg:flex-col',
      row: 'lg:flex-row',
      wrap: 'lg:flex-wrap',
      nowrap: 'lg:flex-nowrap',
      center: 'lg:items-center lg:justify-center',
      between: 'lg:justify-between',
      start: 'lg:justify-start',
      end: 'lg:justify-end',
    },
    text: {
      xs: 'lg:text-xs',
      sm: 'lg:text-sm',
      base: 'lg:text-base',
      lg: 'lg:text-lg',
      xl: 'lg:text-xl',
      '2xl': 'lg:text-2xl',
      '3xl': 'lg:text-3xl',
      '4xl': 'lg:text-4xl',
      center: 'lg:text-center',
      left: 'lg:text-left',
      right: 'lg:text-right',
    },
    width: {
      full: 'lg:w-full',
      half: 'lg:w-1/2',
      third: 'lg:w-1/3',
      quarter: 'lg:w-1/4',
      auto: 'lg:w-auto',
    },
    height: {
      full: 'lg:h-full',
      screen: 'lg:h-screen',
      auto: 'lg:h-auto',
      h16: 'lg:h-16',
      h20: 'lg:h-20',
    },
    position: {
      relative: 'lg:relative',
      absolute: 'lg:absolute',
      fixed: 'lg:fixed',
      sticky: 'lg:sticky',
    },
    grid: {
      cols1: 'lg:grid-cols-1',
      cols2: 'lg:grid-cols-2',
      cols3: 'lg:grid-cols-3',
      cols4: 'lg:grid-cols-4',
      gap2: 'lg:gap-2',
      gap4: 'lg:gap-4',
      gap6: 'lg:gap-6',
      gap8: 'lg:gap-8',
    },
    gap: {
      gap2: 'lg:gap-2',
      gap4: 'lg:gap-4',
      gap6: 'lg:gap-6',
      gap8: 'lg:gap-8',
      gap10: 'lg:gap-10',
    },
  };
  
  export const tabletOnly = {
    // Classes que só funcionam em tablet (≥ 768px)
    margin: {
      mb2: 'md:mb-2',
      mb4: 'md:mb-4',
      mb6: 'md:mb-6',
      mb8: 'md:mb-8',
      mb12: 'md:mb-12',
      mb16: 'md:mb-16',
      mb24: 'md:mb-24',
      mb32: 'md:mb-32',
      mt2: 'md:mt-2',
      mt4: 'md:mt-4',
      mt6: 'md:mt-6',
      mt8: 'md:mt-8',
      mt12: 'md:mt-12',
      mt16: 'md:mt-16',
      mt24: 'md:mt-24',
      mt32: 'md:mt-32',
    },
    padding: {
      p2: 'md:p-2',
      p4: 'md:p-4',
      p6: 'md:p-6',
      p8: 'md:p-8',
      p12: 'md:p-12',
      p16: 'md:p-16',
      p24: 'md:p-24',
      p32: 'md:p-32',
      px2: 'md:px-2',
      px4: 'md:px-4',
      px6: 'md:px-6',
      px8: 'md:px-8',
      px12: 'md:px-12',
      px16: 'md:px-16',
      py2: 'md:py-2',
      py4: 'md:py-4',
      py6: 'md:py-6',
      py8: 'md:py-8',
      py12: 'md:py-12',
      py16: 'md:py-16',
    },
    display: {
      hidden: 'md:hidden',
      block: 'md:block',
      flex: 'md:flex',
      grid: 'md:grid',
      inline: 'md:inline',
      inlineBlock: 'md:inline-block',
      inlineFlex: 'md:inline-flex',
    },
    flex: {
      col: 'md:flex-col',
      row: 'md:flex-row',
      wrap: 'md:flex-wrap',
      nowrap: 'md:flex-nowrap',
      center: 'md:items-center md:justify-center',
      between: 'md:justify-between',
      start: 'md:justify-start',
      end: 'md:justify-end',
    },
    text: {
      xs: 'md:text-xs',
      sm: 'md:text-sm',
      base: 'md:text-base',
      lg: 'md:text-lg',
      xl: 'md:text-xl',
      '2xl': 'md:text-2xl',
      '3xl': 'md:text-3xl',
      '4xl': 'md:text-4xl',
      center: 'md:text-center',
      left: 'md:text-left',
      right: 'md:text-right',
    },
    width: {
      full: 'md:w-full',
      half: 'md:w-1/2',
      third: 'md:w-1/3',
      quarter: 'md:w-1/4',
      auto: 'md:w-auto',
    },
    height: {
      full: 'md:h-full',
      screen: 'md:h-screen',
      auto: 'md:h-auto',
      h16: 'md:h-16',
      h20: 'md:h-20',
    },
    position: {
      relative: 'md:relative',
      absolute: 'md:absolute',
      fixed: 'md:fixed',
      sticky: 'md:sticky',
    },
    grid: {
      cols1: 'md:grid-cols-1',
      cols2: 'md:grid-cols-2',
      cols3: 'md:grid-cols-3',
      cols4: 'md:grid-cols-4',
      gap2: 'md:gap-2',
      gap4: 'md:gap-4',
      gap6: 'md:gap-6',
      gap8: 'md:gap-8',
    },
    gap: {
      gap2: 'md:gap-2',
      gap4: 'md:gap-4',
      gap6: 'md:gap-6',
      gap8: 'md:gap-8',
      gap10: 'md:gap-10',
    },
  }; 