export const mobileOnly = {
    // Classes que só funcionam em mobile (< 480px)
    colSpan: {
      cols1: 'max-xs:col-span-1',
      cols2: 'max-xs:col-span-2',
      cols3: 'max-xs:col-span-3',
      cols4: 'max-xs:col-span-4',
      cols5: 'max-xs:col-span-5',
      cols6: 'max-xs:col-span-6',
      cols7: 'max-xs:col-span-7',
      cols8: 'max-xs:col-span-8',
      cols9: 'max-xs:col-span-9',
      cols10: 'max-xs:col-span-10',
      cols11: 'max-xs:col-span-11',
      cols12: 'max-xs:col-span-12',
    },
    margin: {
      mb2: 'max-xs:mb-2',
      mb4: 'max-xs:mb-4',
      mb6: 'max-xs:mb-6',
      mb8: 'max-xs:mb-8',
      mb12: 'max-xs:mb-12',
      mb16: 'max-xs:mb-16',
      mb24: 'max-xs:mb-24',
      mb32: 'max-xs:mb-32',
      mt2: 'max-xs:mt-2',
      mt4: 'max-xs:mt-4',
      mt6: 'max-xs:mt-6',
      mt8: 'max-xs:mt-8',
      mt12: 'max-xs:mt-12',
      mt16: 'max-xs:mt-16',
      mt24: 'max-xs:mt-24',
      mt32: 'max-xs:mt-32',
      mx6: 'max-xs:mx-6',
      mx12: 'max-xs:mx-12',
      mx16: 'max-xs:mx-16',
      mx24: 'max-xs:mx-24',
      mx32: 'max-xs:mx-32',      
    },
    padding: {
      p2: 'max-xs:p-2',
      p4: 'max-xs:p-4',
      p6: 'max-xs:p-6',
      p8: 'max-xs:p-8',
      p12: 'max-xs:p-12',
      p16: 'max-xs:p-16',
      p24: 'max-xs:p-24',
      p32: 'max-xs:p-32',
      px2: 'max-xs:px-2',
      px4: 'max-xs:px-4',
      px6: 'max-xs:px-6',
      px8: 'max-xs:px-8',
      px12: 'max-xs:px-12',
      px16: 'max-xs:px-16',
      py2: 'max-xs:py-2',
      py4: 'max-xs:py-4',
      py6: 'max-xs:py-6',
      py8: 'max-xs:py-8',
      py12: 'max-xs:py-12',
      py16: 'max-xs:py-16',
      pt2: 'max-xs:pt-2',
      pt4: 'max-xs:pt-4',
      pt6: 'max-xs:pt-6',
      pt8: 'max-xs:pt-8',
      pt12: 'max-xs:pt-12',
      pt16: 'max-xs:pt-16',
      pb2: 'max-xs:pb-2',
      pb4: 'max-xs:pb-4',
      pb6: 'max-xs:pb-6',
      pb8: 'max-xs:pb-8',
      pb12: 'max-xs:pb-12',
      pb16: 'max-xs:pb-16',
    },
    display: {
      hidden: 'max-xs:hidden',
      block: 'max-xs:block',
      flex: 'max-xs:flex',
      grid: 'max-xs:grid',
      inline: 'max-xs:inline',
      inlineBlock: 'max-xs:inline-block',
      inlineFlex: 'max-xs:inline-flex',
    },
    flexDirection: {
      col: 'max-xs:flex-col',
      row: 'max-xs:flex-row',
      wrap: 'max-xs:flex-wrap',
      nowrap: 'max-xs:flex-nowrap',
    },
    flex: {
      col: 'max-xs:flex-col',
      row: 'max-xs:flex-row',
      wrap: 'max-xs:flex-wrap',
      nowrap: 'max-xs:flex-nowrap',
      center: 'max-xs:items-center max-xs:justify-center',
      between: 'max-xs:justify-between',
      start: 'max-xs:justify-start',
      end: 'max-xs:justify-end',
    },
    text: {
      xs: 'max-xs:text-xs',
      sm: 'max-xs:text-sm',
      base: 'max-xs:text-base',
      lg: 'max-xs:text-lg',
      xl: 'max-xs:text-xl',
      '2xl': 'max-xs:text-2xl',
      '3xl': 'max-xs:text-3xl',
      '4xl': 'max-xs:text-4xl',
      '5xl': 'max-xs:text-5xl', 
      '6xl': 'max-xs:text-6xl',
      '7xl': 'max-xs:text-7xl',
      '8xl': 'max-xs:text-8xl',
      '9xl': 'max-xs:text-9xl',
      '10xl': 'max-xs:text-10xl',
      '11xl': 'max-xs:text-11xl',
      '12xl': 'max-xs:text-12xl',
      center: 'max-xs:text-center',
      left: 'max-xs:text-left',
      right: 'max-xs:text-right',
    },
    width: {
      full: 'max-xs:w-full',
      half: 'max-xs:w-1/2',
      third: 'max-xs:w-1/3',
      quarter: 'max-xs:w-1/4',
      auto: 'max-xs:w-auto',
    },
    height: {
      full: 'max-xs:h-full',
      screen: 'max-xs:h-screen',
      auto: 'max-xs:h-auto',
      h16: 'max-xs:h-16',
      h20: 'max-xs:h-20',
    },
    position: {
      relative: 'max-xs:relative',
      absolute: 'max-xs:absolute',
      fixed: 'max-xs:fixed',
      sticky: 'max-xs:sticky',
    },
    grid: {
      cols1: 'max-xs:grid-cols-1',
      cols2: 'max-xs:grid-cols-2',
      cols3: 'max-xs:grid-cols-3',
      cols4: 'max-xs:grid-cols-4',
      gap2: 'max-xs:gap-2',
      gap4: 'max-xs:gap-4',
      gap6: 'max-xs:gap-6',
      gap8: 'max-xs:gap-8',
    },
    gap: {
      gap2: 'max-xs:gap-2',
      gap4: 'max-xs:gap-4',
      gap6: 'max-xs:gap-6',
      gap8: 'max-xs:gap-8',
      gap10: 'max-xs:gap-10',
    },
    container: "grid grid-cols-12 gap-6 p-4"
  };
  
  export const desktopOnly = {
    // Classes que só funcionam em desktop (≥ 1024px)
    colSpan: {
      cols1: 'lg:col-span-1',
      cols2: 'lg:col-span-2',
      cols3: 'lg:col-span-3',
      cols4: 'lg:col-span-4',
      cols5: 'lg:col-span-5',
      cols6: 'lg:col-span-6',
      cols7: 'lg:col-span-7',
      col8: 'lg:col-span-8',
      cols9: 'lg:col-span-9',
      cols10: 'lg:col-span-10',
      cols11: 'lg:col-span-11',
      cols12: 'lg:col-span-12',
    },

    margin: {
      mb2: 'lg:mb-2',
      mb4: 'lg:mb-4',
      mb6: 'lg:mb-6',
      mb8: 'lg:mb-8',
      mb12: 'lg:mb-12',
      mb16: 'lg:mb-16',
      mb24: 'lg:mb-24',
      mb32: 'lg:mb-32',
      mt2: 'lg:mt-2',
      mt4: 'lg:mt-4',
      mt6: 'lg:mt-6',
      mt8: 'lg:mt-8',
      mt12: 'lg:mt-12',
      mt16: 'lg:mt-16',
      mt24: 'lg:mt-24',
      mt32: 'lg:mt-32',
      mx6: 'lg:mx-6',
      mx12: 'lg:mx-12',
      mx16: 'lg:mx-16',
      mx24: 'lg:mx-24',
      mx32: 'lg:mx-32',
      mx48: 'lg:mx-48',
    },
    padding: {
      p2: 'lg:p-2',
      p4: 'lg:p-4',
      p6: 'lg:p-6',
      p8: 'lg:p-8',
      p12: 'lg:p-12',
      p16: 'lg:p-16',
      p24: 'lg:p-24',
      p32: 'lg:p-32',
      px2: 'lg:px-2',
      px4: 'lg:px-4',
      px6: 'lg:px-6',
      px8: 'lg:px-8',
      px12: 'lg:px-12',
      px16: 'lg:px-16',
      py2: 'lg:py-2',
      py4: 'lg:py-4',
      py6: 'lg:py-6',
      py8: 'lg:py-8',
      py12: 'lg:py-12',
      py16: 'lg:py-16',
      pt9:   'lg:pt-9',
      pt10:  'lg:pt-10',
      pt11:  'lg:pt-11',
      pt12: 'lg:pt-12',
      pt13: 'lg:pt-13',
      pt14: 'lg:pt-14',
      pt15: 'lg:pt-15',
      pt16: 'lg:pt-16',
      pb12: 'lg:pb-12',
      pb16: 'lg:pb-16',
      pb18: 'lg:pb-18',
      pb20: 'lg:pb-20',
      pb24: 'lg:pb-24',
      pb32: 'lg:pb-32',
    },
    display: {
      hidden: 'lg:hidden',
      block: 'lg:block',
      flex: 'lg:flex',
      grid: 'lg:grid',
      inline: 'lg:inline',
      inlineBlock: 'lg:inline-block',
      inlineFlex: 'lg:inline-flex',
    },
    flex: {
      col: 'lg:flex-col',
      row: 'lg:flex-row',
      wrap: 'lg:flex-wrap',
      nowrap: 'lg:flex-nowrap',
      center: 'lg:items-center lg:justify-center',
      between: 'lg:justify-between',
      start: 'lg:justify-start',
      end: 'lg:justify-end',
    },
    text: {
      xs: 'lg:text-xs',
      sm: 'lg:text-sm',
      base: 'lg:text-base',
      lg: 'lg:text-lg',
      xl: 'lg:text-xl',
      '2xl': 'lg:text-2xl',
      '3xl': 'lg:text-3xl',
      '4xl': 'lg:text-4xl',
      '5xl': 'lg:text-5xl',
      '6xl': 'lg:text-6xl',
      '7xl': 'lg:text-7xl',
      '8xl': 'lg:text-8xl',
      '9xl': 'lg:text-9xl',
      '10xl': 'lg:text-10xl',
      '11xl': 'lg:text-11xl',
      '12xl': 'lg:text-12xl',
      center: 'lg:text-center',
      left: 'lg:text-left',
      right: 'lg:text-right',
    },
    width: {
      full: 'lg:w-full',
      half: 'lg:w-1/2',
      third: 'lg:w-1/3',
      quarter: 'lg:w-1/4',
      auto: 'lg:w-auto',
    },
    height: {
      full: 'lg:h-full',
      screen: 'lg:h-screen',
      auto: 'lg:h-auto',
      h16: 'lg:h-16',
      h20: 'lg:h-20',
    },
    position: {
      relative: 'lg:relative',
      absolute: 'lg:absolute',
      fixed: 'lg:fixed',
      sticky: 'lg:sticky',
    },
    grid: {
      cols1: 'lg:grid-cols-1',
      cols2: 'lg:grid-cols-2',
      cols3: 'lg:grid-cols-3',
      cols4: 'lg:grid-cols-4',
      gap2: 'lg:gap-2',
      gap4: 'lg:gap-4',
      gap6: 'lg:gap-6',
      gap8: 'lg:gap-8',
    },
    gap: {
      gap2: 'lg:gap-2',
      gap4: 'lg:gap-4',
      gap6: 'lg:gap-6',
      gap8: 'lg:gap-8',
      gap10: 'lg:gap-10',
    },
    container: "grid grid-cols-12 gap-6 p-4"
  };
  
  export const tabletOnly = {
    // Classes que só funcionam em tablet (≥ 768px)
    margin: {
      mb2: 'md:mb-2',
      mb4: 'md:mb-4',
      mb6: 'md:mb-6',
      mb8: 'md:mb-8',
      mb12: 'md:mb-12',
      mb16: 'md:mb-16',
      mb24: 'md:mb-24',
      mb32: 'md:mb-32',
      mt2: 'md:mt-2',
      mt4: 'md:mt-4',
      mt6: 'md:mt-6',
      mt8: 'md:mt-8',
      mt12: 'md:mt-12',
      mt16: 'md:mt-16',
      mt24: 'md:mt-24',
      mt32: 'md:mt-32',
    },
    padding: {
      p2: 'md:p-2',
      p4: 'md:p-4',
      p6: 'md:p-6',
      p8: 'md:p-8',
      p12: 'md:p-12',
      p16: 'md:p-16',
      p24: 'md:p-24',
      p32: 'md:p-32',
      px2: 'md:px-2',
      px4: 'md:px-4',
      px6: 'md:px-6',
      px8: 'md:px-8',
      px12: 'md:px-12',
      px16: 'md:px-16',
      py2: 'md:py-2',
      py4: 'md:py-4',
      py6: 'md:py-6',
      py8: 'md:py-8',
      py12: 'md:py-12',
      py16: 'md:py-16',
    },
    display: {
      hidden: 'md:hidden',
      block: 'md:block',
      flex: 'md:flex',
      grid: 'md:grid',
      inline: 'md:inline',
      inlineBlock: 'md:inline-block',
      inlineFlex: 'md:inline-flex',
    },
    flex: {
      col: 'md:flex-col',
      row: 'md:flex-row',
      wrap: 'md:flex-wrap',
      nowrap: 'md:flex-nowrap',
      center: 'md:items-center md:justify-center',
      between: 'md:justify-between',
      start: 'md:justify-start',
      end: 'md:justify-end',
    },
    text: {
      xs: 'md:text-xs',
      sm: 'md:text-sm',
      base: 'md:text-base',
      lg: 'md:text-lg',
      xl: 'md:text-xl',
      '2xl': 'md:text-2xl',
      '3xl': 'md:text-3xl',
      '4xl': 'md:text-4xl',
      center: 'md:text-center',
      left: 'md:text-left',
      right: 'md:text-right',
    },
    width: {
      full: 'md:w-full',
      half: 'md:w-1/2',
      third: 'md:w-1/3',
      quarter: 'md:w-1/4',
      auto: 'md:w-auto',
    },
    height: {
      full: 'md:h-full',
      screen: 'md:h-screen',
      auto: 'md:h-auto',
      h16: 'md:h-16',
      h20: 'md:h-20',
    },
    position: {
      relative: 'md:relative',
      absolute: 'md:absolute',
      fixed: 'md:fixed',
      sticky: 'md:sticky',
    },
    grid: {
      cols1: 'md:grid-cols-1',
      cols2: 'md:grid-cols-2',
      cols3: 'md:grid-cols-3',
      cols4: 'md:grid-cols-4',
      gap2: 'md:gap-2',
      gap4: 'md:gap-4',
      gap6: 'md:gap-6',
      gap8: 'md:gap-8',
    },
    gap: {
      gap2: 'md:gap-2',
      gap4: 'md:gap-4',
      gap6: 'md:gap-6',
      gap8: 'md:gap-8',
      gap10: 'md:gap-10',
    },
  }; 